version: '3.4'

networks:
  vnetbackend:  

services:
  servicio_api:
    container_name: containerproducts
    image: ${DOCKER_REGISTRY-}backendproductsapiimage
    build:
      context: .
      dockerfile: BackEndProducts.Api/Dockerfile
    environment:
      - DB_SERVER_HOST=servicio_contenedorbd
      - DB_SERVER_PORT=1433
      - DB_NAME=BD_Products
      - DB_USER=sa
      - DB_SA_PASSWORD=Password1*      
    networks:
      - vnetbackend
    ports:
      - "13000:8082"
    depends_on:
      - servicio_contenedorbd 
  servicio_contenedorbd:
    container_name: dbcontainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1*
    networks:
      - vnetbackend
    ports:
        - "9001:1433"